name: Generate
on: [push]

jobs:
  table:
    runs-on: ubuntu-latest
    name: Update README from json data
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "npm"
      - run: npm i
      - run: node generate.js
